/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.61
 * Generated at: 2021-05-04 08:40:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("jar:file:/C:/z_sylee/jsp/semi/semi_1/semi01/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/semi/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/member/../view/header.jsp", Long.valueOf(1620095977225L));
    _jspx_dependants.put("/member/../view/../style/header.css", Long.valueOf(1620095977088L));
    _jspx_dependants.put("/member/../view/../style/footer.css", Long.valueOf(1620095977064L));
    _jspx_dependants.put("/member/../view/footer.jsp", Long.valueOf(1620095977150L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1620095977316L));
    _jspx_dependants.put("/member/../view/../style/common.css", Long.valueOf(1620095977042L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>회원가입</title>\r\n");
      out.write("<style>\r\n");
      out.write(".enrollFrm {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input {\r\n");
      out.write("\twidth: 400px;\r\n");
      out.write("\theight: 40px;\r\n");
      out.write("}\r\n");
      out.write("table {\r\n");
      out.write("\tmargin: 0 auto 0 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".required {\r\n");
      out.write("\tcolor: green;\r\n");
      out.write("\tfont-size: 1px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".optional {\r\n");
      out.write("\tcolor: brown;\r\n");
      out.write("\tfont-size: 1px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#idcheck {\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#btnEnroll {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("// 아이디 중복 체크 결과\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t// 아이디 중복 체크\r\n");
      out.write("\t\t$(\"#idcheck\").click(function() {\r\n");
      out.write("\t\t\tvar id = $(\"#id\").val().trim();\r\n");
      out.write("\t\t\tif(id == \"\") {\r\n");
      out.write("\t\t\t\talert(\"아이디를 입력하고 중복확인을 눌러주세요\");\r\n");
      out.write("\t\t\t\t$(\"id\").focus();\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/uniqueid\",\r\n");
      out.write("\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\"id\" : id\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\tif (data == \"사용가능\") {\r\n");
      out.write("\t\t\t\t\t\talert(\"사용 가능한 아이디입니다\");\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\talert(\"이미 존재하는 아이디입니다. 다른 아이디를 사용해주세요\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t// 비밀번호 일치 체크\r\n");
      out.write("\t\t$(\"#password2\").keyup(function() {\r\n");
      out.write("\t\t\tvar pass1 = $(\"#password1\").val();\r\n");
      out.write("\t\t\tvar pass2 = $(\"#password2\").val();\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (pass1 == pass2) {\r\n");
      out.write("\t\t\t\t$(\"#passcheck\").text(\"비밀번호가 일치합니다.\");\r\n");
      out.write("\t\t\t\t$(\"#passcheck\").css(\"color\", \"blue\").css(\"font-size\", \"1px\");\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$(\"#passcheck\").text(\"비밀번호가 일치하지 않습니다.\");\r\n");
      out.write("\t\t\t\t$(\"#passcheck\").css(\"color\", \"red\").css(\"font-size\", \"1px\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t// 필수칸 입력 체크\r\n");
      out.write("\tfunction required() {\r\n");
      out.write("\t\tif ($(\"#id\").val() == \"\") {\r\n");
      out.write("\t\t\talert(\"필수 입력칸입니다\");\r\n");
      out.write("\t\t\t$(\"#id\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif ($(\"#nickname\").val() == \"\") {\r\n");
      out.write("\t\t\talert(\"필수 입력칸입니다\");\r\n");
      out.write("\t\t\t$(\"#nickname\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif ($(\"#password1\").val() == \"\") {\r\n");
      out.write("\t\t\talert(\"필수 입력칸입니다\");\r\n");
      out.write("\t\t\t$(\"#password1\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif ($(\"#password2\").val() == \"\") {\r\n");
      out.write("\t\t\talert(\"필수 입력칸입니다\");\r\n");
      out.write("\t\t\t$(\"#password2\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif ($(\"#passquestion\").val() == \"0\") {\r\n");
      out.write("\t\t\talert(\"비밀번호 질문을 선택하십시오\");\r\n");
      out.write("\t\t\t$(\"#passquestion\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif ($(\"#passanswer\").val() == \"\") {\r\n");
      out.write("\t\t\talert(\"필수 입력칸입니다\");\r\n");
      out.write("\t\t\t$(\"#passanswer\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif ($(\"#agelimit\").is(\":checked\") == false) {\r\n");
      out.write("\t\t\talert(\"만 14세 이상만이 가입할 수 있습니다\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t// 회원가입 입력칸 형식 체크\r\n");
      out.write("\tfunction regCheck() {\r\n");
      out.write("\t\tvar id = $(\"#id\").val().trim();\r\n");
      out.write("\t\tvar reg1 = /^[A-Za-z0-9]{4,15}$/g;\r\n");
      out.write("\r\n");
      out.write("\t\tvar nickname = $(\"#nickname\").val().trim();\r\n");
      out.write("\t\tvar reg2 = /^[가-힣A-Za-z0-9]{1,8}$/g;\r\n");
      out.write("\r\n");
      out.write("\t\tvar password = $(\"#password1\").val().trim();\r\n");
      out.write("\t\tvar reg3 = /^[A-Za-z0-9!@#$%^&*]{8,15}$/g;\r\n");
      out.write("\r\n");
      out.write("\t\tvar passanswer = $(\"#passanswer\").val().trim();\r\n");
      out.write("\t\tvar reg4 = /^[가-힣A-Za-z0-9]{1,20}$/g;\r\n");
      out.write("\r\n");
      out.write("\t\tvar tel = $(\"#tel\").val().trim();\r\n");
      out.write("\t\tvar reg5 = /^[0-9]{10,13}$/;\r\n");
      out.write("\r\n");
      out.write("\t\tvar email = $(\"#email\").val().trim();\r\n");
      out.write("\t\tvar reg6 = /^[A-Za-z0-9]+@[A-Za-z0-9]+\\.[A-Za-z0-9]+$/g;\r\n");
      out.write("\r\n");
      out.write("\t\tif (!reg1.test(id)) {\r\n");
      out.write("\t\t\talert(\"아이디 형식이 잘못되었습니다\");\r\n");
      out.write("\t\t\t$(\"#id\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (!reg2.test(nickname)) {\r\n");
      out.write("\t\t\talert(\"닉네임 형식이 잘못되었습니다\");\r\n");
      out.write("\t\t\t$(\"#nickname\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (!reg3.test(password)) {\r\n");
      out.write("\t\t\talert(\"비밀번호 형식이 잘못되었습니다\");\r\n");
      out.write("\t\t\t$(\"#password1\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (!reg4.test(passanswer)) {\r\n");
      out.write("\t\t\talert(\"비밀번호 답변 형식이 잘못되었습니다\");\r\n");
      out.write("\t\t\t$(\"#passanswer\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif (!reg5.test(tel) && (tel != \"\")) {\r\n");
      out.write("\t\t\talert(\"전화번호 형식이 잘못되었습니다\");\r\n");
      out.write("\t\t\t$(\"#tel\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif (!reg6.test(email) && (email != \"\")) {\r\n");
      out.write("\t\t\talert(\"이메일 형식이 잘못되었습니다\");\r\n");
      out.write("\t\t\t$(\"#email\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t// 비밀번호 일치 체크\r\n");
      out.write("\tfunction passequal() {\r\n");
      out.write("\t\tif ($(\"#password1\").val() != $(\"#password2\").val()) {\r\n");
      out.write("\t\t\talert(\"비밀번호가 일치하지 않습니다\");\r\n");
      out.write("\t\t\t$(\"#password1\").val(\"\");\r\n");
      out.write("\t\t\t$(\"#password2\").val(\"\");\r\n");
      out.write("\t\t\t$(\"#password1\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t// 회원가입 버튼 눌렀을 때,\r\n");
      out.write("\tfunction admit() {\r\n");
      out.write("\t\tif (required() == false) {\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif (regCheck() == false) {\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif (passequal() == false) {\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t// 다 충족 되었다면\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t};\r\n");
      out.write("\r\n");
      out.write("\t// 주소 api\r\n");
      out.write("\tfunction sample6_execDaumPostcode() {\r\n");
      out.write("\t\tnew daum.Postcode(\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\toncomplete : function(data) {\r\n");
      out.write("\t\t\t\t\t\tvar addr = ''; // 주소 변수\r\n");
      out.write("\t\t\t\t\t\tvar extraAddr = ''; // 참고항목 변수\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\tif (data.userSelectedType === 'R') { // 사용자가 도로명 주소를 선택했을 경우\r\n");
      out.write("\t\t\t\t\t\t\taddr = data.roadAddress;\r\n");
      out.write("\t\t\t\t\t\t} else { // 사용자가 지번 주소를 선택했을 경우(J)\r\n");
      out.write("\t\t\t\t\t\t\taddr = data.jibunAddress;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\tif (data.userSelectedType === 'R') {\r\n");
      out.write("\t\t\t\t\t\t\tif (data.bname !== ''\r\n");
      out.write("\t\t\t\t\t\t\t\t\t&& /[동|로|가]$/g.test(data.bname)) {\r\n");
      out.write("\t\t\t\t\t\t\t\textraAddr += data.bname;\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\tif (data.buildingName !== ''\r\n");
      out.write("\t\t\t\t\t\t\t\t\t&& data.apartment === 'Y') {\r\n");
      out.write("\t\t\t\t\t\t\t\textraAddr += (extraAddr !== '' ? ', '\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ data.buildingName : data.buildingName);\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\tif (extraAddr !== '') {\r\n");
      out.write("\t\t\t\t\t\t\t\textraAddr = ' (' + extraAddr + ')';\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"sample6_extraAddress\").value = extraAddr;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"sample6_extraAddress\").value = '';\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById('sample6_postcode').value = data.zonecode;\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById(\"sample6_address\").value = addr;\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById(\"sample6_detailAddress\")\r\n");
      out.write("\t\t\t\t\t\t\t\t.focus();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}).open();\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("@charset \"UTF-8\";\r\n");
      out.write("/*ê³µíµ ì¤ì */\r\n");
      out.write("html, body {\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("\theight: calc(100% - 100px);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("* {\r\n");
      out.write("\tmargin-top: 0;\r\n");
      out.write("\tjustify-content: center !important;\r\n");
      out.write("\tfont-family: Montserrat;\r\n");
      out.write("\tfont-weight: 700;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".content {\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\twidth : 1240px;\r\n");
      out.write("\theight: calc(100% - 100px);\r\n");
      out.write("\tmargin-top: 124px;\r\n");
      out.write("\tmargin-left: auto;\r\n");
      out.write("\tmargin-right: auto;\r\n");
      out.write("\tmargin-bottom: 0px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\twidth: 1240px;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*bootstrap boxì footerìë§ ì ì©ëë ì¬í­*/\r\n");
      out.write(".container {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tmax-width: 1240px;\r\n");
      out.write("\tpadding-right: 1.5rem;\r\n");
      out.write("\tpadding-left: 1.5rem;\r\n");
      out.write("\tmargin-right: auto;\r\n");
      out.write("\tmargin-left: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".row {\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\tflex-wrap: wrap;\r\n");
      out.write("\tmargin-right: -1.5rem;\r\n");
      out.write("\tmargin-left: -1.5rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".justify-content-center {\r\n");
      out.write("\tjustify-content: center !important;\r\n");
      out.write("\tmargin-top: 3rem !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".col-xl, .col-xl-auto, .col-xl-12, .col-xl-11, .col-xl-10, .col-xl-9,\r\n");
      out.write("\t.col-xl-8, .col-xl-7, .col-xl-6, .col-xl-5, .col-xl-4, .col-xl-3,\r\n");
      out.write("\t.col-xl-2, .col-xl-1, .col-lg, .col-lg-auto, .col-lg-12, .col-lg-11,\r\n");
      out.write("\t.col-lg-10, .col-lg-9, .col-lg-8, .col-lg-7, .col-lg-6, .col-lg-5,\r\n");
      out.write("\t.col-lg-4, .col-lg-3, .col-lg-2, .col-lg-1, .col-md, .col-md-auto,\r\n");
      out.write("\t.col-md-12, .col-md-11, .col-md-10, .col-md-9, .col-md-8, .col-md-7,\r\n");
      out.write("\t.col-md-6, .col-md-5, .col-md-4, .col-md-3, .col-md-2, .col-md-1,\r\n");
      out.write("\t.col-sm, .col-sm-auto, .col-sm-12, .col-sm-11, .col-sm-10, .col-sm-9,\r\n");
      out.write("\t.col-sm-8, .col-sm-7, .col-sm-6, .col-sm-5, .col-sm-4, .col-sm-3,\r\n");
      out.write("\t.col-sm-2, .col-sm-1, .col, .col-auto, .col-12, .col-11, .col-10,\r\n");
      out.write("\t.col-9, .col-8, .col-7, .col-6, .col-5, .col-4, .col-3, .col-2, .col-1\r\n");
      out.write("\t{\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tpadding-right: 1.5rem;\r\n");
      out.write("\tpadding-left: 1.5rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".col-md-6 {\r\n");
      out.write("\tflex: 0 0 50%;\r\n");
      out.write("\tmax-width: 50%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".col-lg-4 {\r\n");
      out.write("\tflex: 0 0 25%;\r\n");
      out.write("\tmax-width: 25%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mb-5 {\r\n");
      out.write("\tmargin-bottom: 3rem !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mb-4 {\r\n");
      out.write("\tmargin-bottom: 1.5rem !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mb-0 {\r\n");
      out.write("\tmargin-bottom: 0 !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mx-auto {\r\n");
      out.write("\tmargin-right: auto !important;\r\n");
      out.write("\tmargin-left: auto !important;\r\n");
      out.write("}");
      out.write('\r');
      out.write('\n');
      out.write("@charset \"UTF-8\";\r\n");
      out.write("/*header*/\r\n");
      out.write(".header {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 100px;\r\n");
      out.write("\tposition: fixed;\r\n");
      out.write("\ttop: 0;\r\n");
      out.write("\tleft: 0;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tz-index: 1000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header-content {\r\n");
      out.write("\tleft: 0;\r\n");
      out.write("\tright: 0;\r\n");
      out.write("\tmargin-left: auto;\r\n");
      out.write("\tmargin-right: auto;\r\n");
      out.write("\tmax-width: 1240px;\r\n");
      out.write("\tmin-width: 645px;\r\n");
      out.write("\theight: 100px;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tbackground-color: #2c3e50;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#logo {\r\n");
      out.write("\tmargin: 10px;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav {\r\n");
      out.write("\twidth: 400px;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tmargin-top: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a:viseted {\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a:hover {\r\n");
      out.write("\tcolor: #1abc9c;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*ë¡ê·¸ì¸ ì */\r\n");
      out.write(".beforeLogin {\r\n");
      out.write("\tmargin-top: 38px;\r\n");
      out.write("\tmargin-right: 10px;\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*ë¡ê·¸ì¸ í*/\r\n");
      out.write(".dropdown {\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("\tmargin-top: 25px;\r\n");
      out.write("\tmargin-right: 10px;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".picBtn {\r\n");
      out.write("\twidth: 50px;\r\n");
      out.write("\theight: 50px;\r\n");
      out.write("\tborder-radius: 50%;\r\n");
      out.write("\tborder: 1px solid white;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pic {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\tobject-fit: cover;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-content {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tmin-width: 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-content a {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tmargin: 10px;\r\n");
      out.write("\tline-height: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown:hover .picBtn {\r\n");
      out.write("\tborder: 1px solid red;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown:hover .dropdown-content {\r\n");
      out.write("\tbackground-color: #ddd;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("}");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<title>\r\n");
      out.write("\t구해줘! 잡스\r\n");
      out.write("</title>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("\t<div class=\"header-content\">\r\n");
      out.write("\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/index.jsp\"> \r\n");
      out.write("\t\t<img alt=\"logo\" src=\"http://ipsumimage.appspot.com/80x80?l=로고\" id=\"logo\">\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t<div class=\"nav\">\r\n");
      out.write("\t\t\t<a href=\"\" id=\"qnaBtn\">질문방</a> \r\n");
      out.write("\t\t\t<a href=\"\" id=\"studyBtn\">스터디방</a> \r\n");
      out.write("\t\t\t<a href=\"\" id=\"reviewBtn\">리뷰방</a> \r\n");
      out.write("\t\t\t<a href=\"\" id=\"shopBtn\">쇼핑방</a> \r\n");
      out.write("\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/calendar/start.jsp\" id=\"recruitBtn\">공채캘린더</a>\r\n");
      out.write("\t\t\t<a href=\"\" id=\"aboutusBtn\">자사소개</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t");
      //  c:choose
      org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
      boolean _jspx_th_c_005fchoose_005f0_reused = false;
      try {
        _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fchoose_005f0.setParent(null);
        int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
        if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t");
            //  c:when
            org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
            boolean _jspx_th_c_005fwhen_005f0_reused = false;
            try {
              _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
              _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
              // /member/../view/header.jsp(27,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginMember == null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
              int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
              if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  out.write("\r\n");
                  out.write("\t\t\t\t<div class=\"beforeLogin\">\r\n");
                  out.write("\t\t\t\t\t<button type=\"button\" id=\"btnLogin\" onclick=\"location.href='");
                  out.print(request.getContextPath());
                  out.write("/member/login.jsp'\">로그인</button>\r\n");
                  out.write("\t\t\t\t\t<button type=\"button\" id=\"btnEnroll\" onclick=\"location.href='");
                  out.print(request.getContextPath());
                  out.write("/member/signup.jsp'\">회원가입</button>\r\n");
                  out.write("\t\t\t\t</div>\r\n");
                  out.write("\t\t\t");
                  int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
              _jspx_th_c_005fwhen_005f0_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
            }
            out.write("\r\n");
            out.write("\t\t\t");
            //  c:when
            org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
            boolean _jspx_th_c_005fwhen_005f1_reused = false;
            try {
              _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
              _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
              // /member/../view/header.jsp(33,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginMember != null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
              int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
              if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  out.write("\r\n");
                  out.write("\t\t\t\t<div class=\"afterLogin\">\r\n");
                  out.write("\t\t\t\t\t<div class=\"dropdown\">\r\n");
                  out.write("\t\t\t\t\t\t<div class=\"picBtn\">\r\n");
                  out.write("\t\t\t\t\t\t\t<img alt=\"profilePic\"\r\n");
                  out.write("\t\t\t\t\t\t\t\tsrc=\"http://ipsumimage.appspot.com/50x50?l=이미지\" class=\"pic\">\r\n");
                  out.write("\t\t\t\t\t\t</div>\r\n");
                  out.write("\t\t\t\t\t\t<div class=\"dropdown-content\">\r\n");
                  out.write("\t\t\t\t\t\t\t<a href=\"");
                  out.print(request.getContextPath());
                  out.write("/myPage/myPageEnter.jsp\">마이페이지</a>\r\n");
                  out.write("\t\t\t\t\t\t\t<a href=\"");
                  out.print(request.getContextPath());
                  out.write("/memberlogout\">로그아웃</a> \r\n");
                  out.write("\t\t\t\t\t\t</div>\r\n");
                  out.write("\t\t\t\t\t</div>\r\n");
                  out.write("\t\t\t\t</div>\r\n");
                  out.write("\t\t\t");
                  int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
              _jspx_th_c_005fwhen_005f1_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
            }
            out.write("\r\n");
            out.write("\t\t");
            int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
        _jspx_th_c_005fchoose_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
      }
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<body class=\"content\">\r\n");
      out.write("\t<div class=\"enrollFrm\">\r\n");
      out.write("\t\t<h1>회원가입</h1>\r\n");
      out.write("\t\t<form action=\"");
      out.print(request.getContextPath());
      out.write("/memberinsert\"\r\n");
      out.write("\t\t\tmethod=\"post\">\r\n");
      out.write("\t\t\t<span id=\"idcheck\">중복확인</span>\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>아이디<span class=\"required\">(필수)</span></td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"id\" id=\"id\"></td>\r\n");
      out.write("\t\t\t\t\t<td><span style=\"font-size: 1px\"> 4~15자의 영문자, 숫자만 사용\r\n");
      out.write("\t\t\t\t\t\t\t가능합니다.</span></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>닉네임<span class=\"required\">(필수)</span></td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"nickname\" id=\"nickname\"></td>\r\n");
      out.write("\t\t\t\t\t<td><span style=\"font-size: 1px\"> 1~8자의 한글, 영문자, 숫자만 사용\r\n");
      out.write("\t\t\t\t\t\t\t가능합니다.</span></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>비밀번호<span class=\"required\">(필수)</span></td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"password\" name=\"password1\" id=\"password1\"></td>\r\n");
      out.write("\t\t\t\t\t<td><span style=\"font-size: 1px\"> 8~15자의 영문자, 숫자,\r\n");
      out.write("\t\t\t\t\t\t\t특수문자(!, @, #, $, %, ^, &, *)만 사용 가능합니다.</span></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>비밀번호 확인<span class=\"required\">(필수)</span></td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"password\" name=\"password2\" id=\"password2\"></td>\r\n");
      out.write("\t\t\t\t\t<td><span id=\"passcheck\"></span></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>비밀번호 질문<span class=\"required\">(필수)</span></td>\r\n");
      out.write("\t\t\t\t\t<td><select name=\"passquestion\" id=\"passquestion\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"0\">비밀번호 질문을 선택해주세요</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"1\">첫 수학여행 장소는?</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"2\">가장 친한 친구의 이름은?</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"3\">첫 해외여행지는?</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"4\">어린시절 자신의 별명은?</option>\r\n");
      out.write("\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>비밀번호 답변<span class=\"required\">(필수)</span></td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"passanswer\" id=\"passanswer\"></td>\r\n");
      out.write("\t\t\t\t\t<td><span style=\"font-size: 1px\"> 1~20자의 한글, 영문자, 숫자만\r\n");
      out.write("\t\t\t\t\t\t\t사용 가능합니다.</span></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>주소<span class=\"optional\">(선택)</span></td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"sample6_postcode\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"우편번호\" name=\"postcode\" readonly> <br> <input\r\n");
      out.write("\t\t\t\t\t\ttype=\"text\" id=\"sample6_address\" placeholder=\"주소\" name=\"address1\"\r\n");
      out.write("\t\t\t\t\t\treadonly><br> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\tid=\"sample6_detailAddress\" placeholder=\"상세주소\" name=\"address2\"><br>\r\n");
      out.write("\t\t\t\t\t\t<!-- 참고항목은 도로명 주소 클릭 시, 동을 표시한다 --> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\tid=\"sample6_extraAddress\" placeholder=\"참고항목\" name=\"address3\"\r\n");
      out.write("\t\t\t\t\t\treadonly></td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"button\" onclick=\"sample6_execDaumPostcode()\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"우편번호 찾기\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>전화번호<span class=\"optional\">(선택)</span></td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"tel\" id=\"tel\"></td>\r\n");
      out.write("\t\t\t\t\t<td><span style=\"font-size: 1px\"> 10~13자의 숫자만 사용 가능합니다.</span></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>이메일<span class=\"optional\">(선택)</span></td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"email\" id=\"email\"></td>\r\n");
      out.write("\t\t\t\t\t<td><span style=\"font-size: 1px\"> 8~15자의 영문자, 숫자,\r\n");
      out.write("\t\t\t\t\t\t\t특수문자(@)만 사용 가능합니다.</span></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"3\"><label><input type=\"checkbox\"\r\n");
      out.write("\t\t\t\t\t\t\tname=\"agree\" value=\"1\" id=\"agelimit\"> 만 14세 이상 회원가입에\r\n");
      out.write("\t\t\t\t\t\t\t동의합니다(필수)</label></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"3\"><label><input type=\"checkbox\"\r\n");
      out.write("\t\t\t\t\t\t\tname=\"agree\" value=\"2\"> 도와줘~ 잡스!의 다양한 소식을 받아보겠습니다(선택)</label></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"3\"><input type=\"submit\" value=\"회원가입\"\r\n");
      out.write("\t\t\t\t\t\tonclick=\"return admit();\" id=\"btnSubmit\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"3\"><input type=\"button\" value=\"로그인으로 이동\"\r\n");
      out.write("\t\t\t\t\t\tonclick=\"location.href='login.jsp'\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("@charset \"UTF-8\";\r\n");
      out.write("/*image*/\r\n");
      out.write(".img-fluid {\r\n");
      out.write("\tmax-width: 100%;\r\n");
      out.write("\theight: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*footer*/\r\n");
      out.write(".footer {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: calc(100% - 100px);\r\n");
      out.write("\tbottom: 0px;\r\n");
      out.write("\tleft: auto;\r\n");
      out.write("\tright: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-content {\r\n");
      out.write("\tbox-sizing: border-box;\r\n");
      out.write("\twidth: 1240px;\r\n");
      out.write("\theight: 100px;\r\n");
      out.write("\tpadding-top: 1rem;\r\n");
      out.write("\tpadding-bottom: 1rem;\r\n");
      out.write("\tbackground-color: #ddd;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tbackground-color: #2c3e50;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".text-uppercase {\r\n");
      out.write("\ttext-transform: uppercase !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".lead {\r\n");
      out.write("\tfont-size: 1.25rem;\r\n");
      out.write("\tfont-weight: 300;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("li {\r\n");
      out.write("\tlist-style:none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-label {\r\n");
      out.write("\tcolor: #add9d4;\r\n");
      out.write("\t\r\n");
      out.write("}");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"footer\">\r\n");
      out.write("\t\t<div class=\"footer-content\">\r\n");
      out.write("\t\t\t<div>(주) 도와줘 잡스씨~</div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><label class=\"footer-label\">만든이</label> 김연준, 이승연, 정재훈,\r\n");
      out.write("\t\t\t\t\t\t제승하, 하도경</li>\r\n");
      out.write("\t\t\t\t\t<li><label class=\"footer-label\">주소지</label> 서울특별시 중구 남대문로 120\r\n");
      out.write("\t\t\t\t\t\t대일빌딩 2F, 3F</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
